### ISSUE TITLE
Support iOS 11 and iOS 12

### ISSUE THREAD

**Issue by devzhr** [ivanvorobei/SPDiffable#3]
**Support iOS 11 and iOS 12**
Improved library to support older versions, we agree with you that the icons are from iOS 13 but we can provide our icons to us the main thing is your ViewController and your cells

**Comment by ivanvorobei** [comment]
Sorry, which icons?

**Comment by devzhr** [comment]
If you put version 13 minimum just for the problem of icons I suggest you put minimum 11 and the target application will add the icons itself

**Comment by ivanvorobei** [comment]
`SPDiffable` don't use any icons
